### ISSUE TITLE
solid vs solidpython

### ISSUE THREAD

**Issue by brettonidas** [whitelynx/parametric-key-tester#1]
There are two modules named "solid" available from PIP. One is installed via pip install solid, and the other solidpython. I only had solid installed, so I was able to import solid, but not the scad_render_to_file() method.

Could you update the README.md to list the dependencies like solidpython?

**Comment by whitelynx** [comment]
@brettonidas Thanks for reporting this! I added a Prerequisites section to the `README.md`.

**Comment by whitelynx** [comment]
Just to follow up, I switched over to a `requirements.txt` and migrated to SolidPython V2.
